name = zombies
depends = default, mobs, moon_phases
optional_depends = farming, currency, tnt, bonemeal, tsm_railcorridors, dungeonsplus, unified_inventory, keys, x_enchanting
description = Adds three styles of zombie that spawn on the surface at night and in dungeons and rail corridors underground. Zombies can be tamed into loyal companions. Built on mobs_redo; model derived from the default player model.
