name = zombies
depends = default, mobs, moon_phases
optional_depends = farming, currency, tnt, bonemeal, tsm_railcorridors, dungeonsplus
description = This mod adds several styles of zombies that spawn on grass at night and in mapgen dungeons. Zombie model derived from the default player model.
